apiVersion: v1
kind: Service
metadata:
  name: pres-frontend
  namespace: planara
spec:
  type: ClusterIP
  selector:
    app: pres-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
